### ISSUE TITLE
Is it possible to make the preprocessing code public?

### ISSUE THREAD

**Issue by cravisjan97** [diegogb/3D_Synthesis_based_on_Fine-grained_Parts#4]
Can you share the pre-processing codes which created the .mat files from  ```./data/input/```. Thanks in advance

**Comment by diegogb** [comment]
Hi cravisjan97:

I have uploaded several additional Matlab files that are part of the pre-processing code.
All the new files are inside the folder "PreprocessUnrevisedCode"

I'd like to highlight the word "Unrevised" in the name of the folder above. 
The code that I have uploaded into this folder was not revised before publishing our article at Shape Modeling International, (SMI 2018).

Also, I am not sure if the code that I uploaded in the folder "PreprocessUnrevisedCode" is complete or if some functions (Matlab scripts) might be missing.
It's been several years since I worked on this code and I had to look into some old backups to find these files, so I apologize in advance if maybe something is missing
