### ISSUE TITLE
How do you obtain mesh segments corresponding to point cloud segments?

### ISSUE THREAD

**Issue by cravisjan97** [diegogb/3D_Synthesis_based_on_Fine-grained_Parts#6]
![Capture](https://user-images.githubusercontent.com/11577265/94174227-e1a55d00-fe49-11ea-93ee-9779ec58b347.PNG)
I see this in your paper but there is no algorithm mentioned. I am trying to write the missing parts in the preprocessing code. Thanks in advance!

**Comment by diegogb** [comment]
A part of the algorithm to obtain mesh segments that **roughly** correspond to the point cloud segments is described in Section 5.4.2 
Notice that the point clouds were obtained by sampling a 3d mesh.
Also, the subdivision process is important. Generally speaking, the subdivided mesh needs to have _small_ edges so that the correction of the jagged boundaries can work in a correct manner.
Sorry I cannot be more precise about this algorithm. However, if you read carefully at Section 5.4.2, (especially the parts of Mesh subdivision and Extraction of mesh segments), you will be able to figure out the process.

**NOTE:** If you are really serious about using our synthesis code in your own project or if you're working on a research project maybe you could contact my former supervisor (and co-author of the paper). His name is Oliver van Kaick and you can find out more about his research projects here: http://gigl.scs.carleton.ca/
