### ISSUE TITLE
Which algorithm did you use to calculate height from base for a 3D point cloud?

### ISSUE THREAD

**Issue by cravisjan97** [diegogb/3D_Synthesis_based_on_Fine-grained_Parts#7]
I see this function missing in the pre-processing code and I want to fill this missing part. I could not find the algorithm on the paper.

**Comment by diegogb** [comment]
Section 4 of our paper mentions:
 _"In addition, we normalize our shapes in scale, so that the axis-aligned bound- ing box of each shape is a cube centered at the origin where all point dimensions are in the range [ −1, 1]"_

Additionally, all our shapes are in a "straight position", so to compute the height from the base we can simply measure the abs. difference between the min and max y coordinate of each shape. 
In several cases, (like in the case of many shapes of our Chairs dataset), the height from the base is equal to 2 units. This is because the shapes are centered at the origin and the shape occupies the full height (dimension) in the range [-1,1]
